spring:
  application:
    name: NYU-GateWay

  cloud:
    gateway:
      routes:
        - id: NYU-MAIN
          uri: lb://NYU-MAIN
          predicates:
            Path=/**
        - id: NYU-IMG
          uri: lb://NYU-IMG
          predicates:
            Path=/**
    compatibility-verifier:
      enabled: false

eureka:
  instance:
    appname: NYU-GateWay
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:80/eureka

server:
  port: 82
