# Generated by Django 4.0.1 on 2022-04-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
