# Generated by Django 4.1 on 2022-08-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_admin', '0005_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeid', models.AutoField(db_column='likeId', primary_key=True, serialize=False)),
                ('show', models.IntegerField()),
                ('updatedate', models.DateTimeField(db_column='updateDate')),
            ],
            options={
                'db_table': 'like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.AutoField(db_column='reportId', primary_key=True, serialize=False)),
                ('report', models.TextField()),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(db_column='reviewId', primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('content', models.CharField(max_length=500)),
                ('imagepath', models.TextField(blank=True, db_column='imagePath', null=True)),
                ('show', models.IntegerField()),
                ('registerdate', models.DateField(db_column='registerDate')),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('saveid', models.AutoField(db_column='saveId', primary_key=True, serialize=False)),
                ('show', models.IntegerField()),
                ('updatedate', models.DateTimeField(db_column='updateDate')),
            ],
            options={
                'db_table': 'save',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('supportid', models.AutoField(db_column='supportId', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('registerdate', models.DateField(db_column='registerDate')),
                ('reply', models.IntegerField()),
            ],
            options={
                'db_table': 'support',
                'managed': False,
            },
        ),
    ]
