server:
  port: 80

spring:
  application:
    name: NYU-MAIN
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    host: 127.0.0.1
    password:
    port: 6379

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    url: jdbc:mariadb://localhost:3306/nyu
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer

mybatis:
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.nyanyumserver.nyanyumserver
  mapper-locations: mapper/**/*.xml

s3:
  profile: http://localhost:81/auth/updateProfileImage?uid=%s

eureka:
  instance:
    instance-id: NYU-MAIN
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
