cloud:
  aws:
    s3:
      bucket: nyu-image-bucket-test
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: false
      access-key: AKIA2XDBKJKQL2Y3SYPD
      secret-key: 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

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB